# Site settings
title: Dani Gnibus
email: danielle.n.gnibus.17@dartmouth.edu
url: https://danignibus.github.io
description: "Personal website for Dani Gnibus. Visit to learn more about my projects, interests, and ideas!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: bc188a #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  tertiary: bc1838 #CC0033 red hyperlinks

# Footer settings
footer:
  copyright: Dani Gnibus
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/danignibus
  - title: github
    url: http://github.com/danignibus

# Postal address (add as many lines as necessary)
address:
  - line: Hinman Box 1002, Dartmouth College
  - line: Hanover, NH 03755

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
